name: Dockerrun

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout
      uses: actions/checkout@v2
      with:
        path: builder-repo

    - name: Checkout paketo samples
      uses: actions/checkout@v2
      with:
        repository: paketo-buildpacks/samples
        path: samples

    - name: Create-builder
      id: something
      uses: docker://buildpacksio/pack
      with:
        args: create-builder testbuilder --config builder-repo/builder.toml

    - name: Smoke
      uses: docker://buildpacksio/pack
      with:
        args: build testapp -p samples/nodejs/yarn --builder testbuilder
