name: Dockerrun

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: builder-repo

    - name: Checkout paketo samples
      uses: actions/checkout@v2
      with:
        repository: paketo-buildpacks/samples
        path: samples

    - name: Install pack
      run: |
        id=$(docker create buildpacksio/pack)
        docker cp $id:pack - > /usr/local/bin/path
        docker rm -v $id

    - name: Smoke
      run: |
        pack create-builder testbuilder --config builder-repo/builder.toml
