name: Dockercp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install pack
      run: |
        id=$(docker create buildpacksio/pack)
        docker sudo cp $id:/layers/paketo-buildpacks_go-build/targets/bin/pack /usr/local/bin/
        docker rm -v $id

    - name: Smoke
      run: |
        pack --version
        pack create-builder testbuilder --config builder.toml
