name: Dockerrun

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create-builder
      id: something
      uses: docker://buildpacksio/pack
      with:
        args: create-builder testbuilder --config builder.toml

    - name: Version
      uses: docker://buildpacksio/pack
      with:
        args: version
