# This is a basic workflow to help you get started with Actions

name: Pass

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      id: something
      run: |
        content=$(cat <<EOF
        [[order]]
        group = [
          { id = "paketo-buildpacks/java-native-image" },
        ]

        [[order]]
        group = [
          { id = "paketo-buildpacks/java" },
        ]

        [[order]]
        group = [
         { id = "paketo-buildpacks/nodejs" },
        ]
        EOF)
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        echo "::set-output name=id::${content}"

    - name: Print passed
      run: |
        echo '${{ steps.something.outputs.id }}'
