# This workflow triggers on a published release event.
# Requires the following secrets:
# - LANGUAGE_FAMILY_REPO -> comma-separated list of repos that should receive the dispatch event
#   (eg. "paketo-buildpacks/nodejs, paketo-buildpacks/dotnet-core")
# - PAKETO_BOT_GITHUB_TOKEN -> a token with permissions to send the dispatch to the language family repo

name: Send Dependency Update Dispatch

on:
  push:
    branches: [ master ]

jobs:

  dispatch:
    runs-on: ubuntu-latest
    name: Send Dispatch
    steps:

    - name: Check out
      uses: actions/checkout@v2

    - name: Parse ID and Version
      id: dependency
      run: |
        echo "::set-output name=id::someid"
        echo "::set-output name=version:someversion"

    - name: List enrolled language families
      id: language-families
      run : |
        if [ ! -f .github/language-family-membership ]; then
          echo "requires line record file .github/language-family-membership"
          exit 1
        fi
        list=$(awk -vORS=, '{print}' .github/language-family-membership | sed 's#,$#\n#')
        echo "::set-output name=list::$list"

    # Generic repository dispatch sender.
    - name: Send Repository Dispatch
      uses: paketo-buildpacks/github-config/actions/dispatch@main
      with:
        repos: ${{ steps.language-families.outputs.list }}
        token: ${{ secrets.MY_TOKEN }}
        event: dependency-update
        payload: |
          {
            "strategy": "replace",
            "dependency": {
              "id": "${{ steps.dependency.outputs.id }}",
              "version": "${{ steps.dependency.outputs.version }}"
            }
          }
